### ISSUE TITLE
Fails to compile with openssl-1.1.1

### ISSUE THREAD

**Issue by DigiAngel** [libevent/libevent#402]
Here's the output..thank you:
~~~
make  all-recursive
make[1]: Entering directory `/home/nobackup/build/libevent-2.0.22-stable'
Making all in .
make[2]: Entering directory `/home/nobackup/build/libevent-2.0.22-stable'
/bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./compat -I./include -I./include  -I/opt/openssl/include  -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c -o bufferevent_openssl.lo bufferevent_openssl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./compat -I./include -I./include -I/opt/openssl/include -g -O2 -Wall -fno-strict-aliasing -pthread -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c bufferevent_openssl.c  -fPIC -DPIC -o .libs/bufferevent_openssl.o
bufferevent_openssl.c: In function 'bio_bufferevent_new':
bufferevent_openssl.c:106:3: error: dereferencing pointer to incomplete type
  b->init = 0;
   ^
bufferevent_openssl.c:107:3: error: dereferencing pointer to incomplete type
  b->num = -1;
   ^
bufferevent_openssl.c:108:3: error: dereferencing pointer to incomplete type
  b->ptr = NULL; /* We'll be putting the bufferevent in this field.*/
   ^
bufferevent_openssl.c:109:3: error: dereferencing pointer to incomplete type
  b->flags = 0;
   ^
bufferevent_openssl.c: In function 'bio_bufferevent_free':
bufferevent_openssl.c:119:7: error: dereferencing pointer to incomplete type
  if (b->shutdown) {
       ^
bufferevent_openssl.c:120:8: error: dereferencing pointer to incomplete type
   if (b->init && b->ptr)
        ^
bufferevent_openssl.c:120:19: error: dereferencing pointer to incomplete type
   if (b->init && b->ptr)
                   ^
bufferevent_openssl.c:121:22: error: dereferencing pointer to incomplete type
    bufferevent_free(b->ptr);
                      ^
bufferevent_openssl.c:122:4: error: dereferencing pointer to incomplete type
   b->init = 0;
    ^
bufferevent_openssl.c:123:4: error: dereferencing pointer to incomplete type
   b->flags = 0;
    ^
bufferevent_openssl.c:124:4: error: dereferencing pointer to incomplete type
   b->ptr = NULL;
    ^
bufferevent_openssl.c: In function 'bio_bufferevent_read':
bufferevent_openssl.c:140:8: error: dereferencing pointer to incomplete type
  if (!b->ptr)
        ^
bufferevent_openssl.c:143:33: error: dereferencing pointer to incomplete type
  input = bufferevent_get_input(b->ptr);
                                 ^
bufferevent_openssl.c: In function 'bio_bufferevent_write':
bufferevent_openssl.c:159:31: error: dereferencing pointer to incomplete type
  struct bufferevent *bufev = b->ptr;
                               ^
bufferevent_openssl.c:165:8: error: dereferencing pointer to incomplete type
  if (!b->ptr)
        ^
bufferevent_openssl.c: In function 'bio_bufferevent_ctrl':
bufferevent_openssl.c:191:31: error: dereferencing pointer to incomplete type
  struct bufferevent *bufev = b->ptr;
                               ^
bufferevent_openssl.c:196:10: error: dereferencing pointer to incomplete type
   ret = b->shutdown;
          ^
bufferevent_openssl.c:199:4: error: dereferencing pointer to incomplete type
   b->shutdown = (int)num;
    ^
bufferevent_openssl.c: At top level:
bufferevent_openssl.c:228:1: error: variable 'methods_bufferevent' has initializer but incomplete type
 static BIO_METHOD methods_bufferevent = {
 ^
bufferevent_openssl.c:229:2: warning: excess elements in struct initializer [enabled by default]
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^
bufferevent_openssl.c:229:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:229:2: warning: excess elements in struct initializer [enabled by default]
bufferevent_openssl.c:229:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:230:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_write,
  ^
bufferevent_openssl.c:230:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:231:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_read,
  ^
bufferevent_openssl.c:231:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:232:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_puts,
  ^
bufferevent_openssl.c:232:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:233:2: warning: excess elements in struct initializer [enabled by default]
  NULL /* bio_bufferevent_gets */,
  ^
bufferevent_openssl.c:233:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:234:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_ctrl,
  ^
bufferevent_openssl.c:234:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:235:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_new,
  ^
bufferevent_openssl.c:235:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:236:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_free,
  ^
bufferevent_openssl.c:236:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:237:2: warning: excess elements in struct initializer [enabled by default]
  NULL /* callback_ctrl */,
  ^
bufferevent_openssl.c:237:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c: In function 'BIO_new_bufferevent':
bufferevent_openssl.c:257:8: error: dereferencing pointer to incomplete type
  result->init = 1;
        ^
bufferevent_openssl.c:258:8: error: dereferencing pointer to incomplete type
  result->ptr = bufferevent;
        ^
bufferevent_openssl.c:259:8: error: dereferencing pointer to incomplete type
  result->shutdown = close_flag ? 1 : 0;
        ^
make[2]: *** [bufferevent_openssl.lo] Error 1
make[2]: Leaving directory `/home/nobackup/build/libevent-2.0.22-stable'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/nobackup/build/libevent-2.0.22-stable'
make: *** [all] Error 2
~~~

**Comment by azat** [comment]
@DigiAngel , can you please try to backport #397 ?
Or even better use *2.1.6* instead of *2.0.x*

**Comment by DigiAngel** [comment]
Oh cool yea...I'll have that a shot and report my findings thank you.

**Comment by DigiAngel** [comment]
And from the latest libevent git:
~~~
  GEN      test/rpcgen-attempted
  GEN      include/event2/event-config.h
make  all-am
make[1]: Entering directory `/home/nobackup/build/libevent'
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_pair.lo
  CC       bufferevent_ratelim.lo
  CC       bufferevent_sock.lo
  CC       event.lo
  CC       evmap.lo
  CC       evthread.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       evutil_time.lo
  CC       listener.lo
  CC       log.lo
  CC       strlcpy.lo
  CC       select.lo
  CC       poll.lo
  CC       epoll.lo
  CC       signal.lo
  CC       evdns.lo
  CC       event_tagging.lo
  CC       evrpc.lo
  CC       http.lo
  CCLD     libevent.la
  CCLD     libevent_core.la
  CCLD     libevent_extra.la
  CC       evthread_pthread.lo
  CCLD     libevent_pthreads.la
  CC       libevent_openssl_la-bufferevent_openssl.lo
bufferevent_openssl.c: In function 'bio_bufferevent_new':
bufferevent_openssl.c:112:3: error: dereferencing pointer to incomplete type
  b->init = 0;
   ^
bufferevent_openssl.c:113:3: error: dereferencing pointer to incomplete type
  b->num = -1;
   ^
bufferevent_openssl.c:114:3: error: dereferencing pointer to incomplete type
  b->ptr = NULL; /* We'll be putting the bufferevent in this field.*/
   ^
bufferevent_openssl.c:115:3: error: dereferencing pointer to incomplete type
  b->flags = 0;
   ^
bufferevent_openssl.c: In function 'bio_bufferevent_free':
bufferevent_openssl.c:125:7: error: dereferencing pointer to incomplete type
  if (b->shutdown) {
       ^
bufferevent_openssl.c:126:8: error: dereferencing pointer to incomplete type
   if (b->init && b->ptr)
        ^
bufferevent_openssl.c:126:19: error: dereferencing pointer to incomplete type
   if (b->init && b->ptr)
                   ^
bufferevent_openssl.c:127:22: error: dereferencing pointer to incomplete type
    bufferevent_free(b->ptr);
                      ^
bufferevent_openssl.c:128:4: error: dereferencing pointer to incomplete type
   b->init = 0;
    ^
bufferevent_openssl.c:129:4: error: dereferencing pointer to incomplete type
   b->flags = 0;
    ^
bufferevent_openssl.c:130:4: error: dereferencing pointer to incomplete type
   b->ptr = NULL;
    ^
bufferevent_openssl.c: In function 'bio_bufferevent_read':
bufferevent_openssl.c:146:8: error: dereferencing pointer to incomplete type
  if (!b->ptr)
        ^
bufferevent_openssl.c:149:33: error: dereferencing pointer to incomplete type
  input = bufferevent_get_input(b->ptr);
                                 ^
bufferevent_openssl.c: In function 'bio_bufferevent_write':
bufferevent_openssl.c:165:31: error: dereferencing pointer to incomplete type
  struct bufferevent *bufev = b->ptr;
                               ^
bufferevent_openssl.c:171:8: error: dereferencing pointer to incomplete type
  if (!b->ptr)
        ^
bufferevent_openssl.c: In function 'bio_bufferevent_ctrl':
bufferevent_openssl.c:197:31: error: dereferencing pointer to incomplete type
  struct bufferevent *bufev = b->ptr;
                               ^
bufferevent_openssl.c:202:10: error: dereferencing pointer to incomplete type
   ret = b->shutdown;
          ^
bufferevent_openssl.c:205:4: error: dereferencing pointer to incomplete type
   b->shutdown = (int)num;
    ^
bufferevent_openssl.c: At top level:
bufferevent_openssl.c:234:1: error: variable 'methods_bufferevent' has initializer but incomplete type
 static BIO_METHOD methods_bufferevent = {
 ^
bufferevent_openssl.c:235:2: warning: excess elements in struct initializer [enabled by default]
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^
bufferevent_openssl.c:235:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:235:2: warning: excess elements in struct initializer [enabled by default]
bufferevent_openssl.c:235:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:236:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_write,
  ^
bufferevent_openssl.c:236:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:237:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_read,
  ^
bufferevent_openssl.c:237:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:238:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_puts,
  ^
bufferevent_openssl.c:238:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:239:2: warning: excess elements in struct initializer [enabled by default]
  NULL /* bio_bufferevent_gets */,
  ^
bufferevent_openssl.c:239:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:240:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_ctrl,
  ^
bufferevent_openssl.c:240:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:241:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_new,
  ^
bufferevent_openssl.c:241:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:242:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_free,
  ^
bufferevent_openssl.c:242:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:243:2: warning: excess elements in struct initializer [enabled by default]
  NULL /* callback_ctrl */,
  ^
bufferevent_openssl.c:243:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c: In function 'BIO_new_bufferevent':
bufferevent_openssl.c:263:8: error: dereferencing pointer to incomplete type
  result->init = 1;
        ^
bufferevent_openssl.c:264:8: error: dereferencing pointer to incomplete type
  result->ptr = bufferevent;
        ^
bufferevent_openssl.c:265:8: error: dereferencing pointer to incomplete type
  result->shutdown = close_flag ? 1 : 0;
        ^
make[1]: *** [libevent_openssl_la-bufferevent_openssl.lo] Error 1
make[1]: Leaving directory `/home/nobackup/build/libevent'
make: *** [all] Error 2
~~~

Thanks....this is actually compiling off the latest openssl git as well.

**Comment by azat** [comment]
And for latest version you need to apply #397

**Comment by azat** [comment]
Or you can just download tarball from here:
https://github.com/libevent/libevent/archive/a39254c25f32850acbb598936a957982738b68e3.zip

**Comment by DigiAngel** [comment]
Perfect...that worked like a champ...thank you so much!

**Comment by inam09** [comment]
sorry! I was in the src directory . now i run this command this shows so many error like .
bufferevent_openssl.c:106:3: error:

**Comment by smprather** [comment]
I am still getting this error in 2.1.8.

bufferevent_openssl.c: In function ?conn_closed?:
bufferevent_openssl.c:524:7: error: ?SSL_ERROR_WANT_ACCEPT? undeclared (first use in this function)
bufferevent_openssl.c:524:7: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [libevent_openssl_la-bufferevent_openssl.lo] Error 1
make[1]: Leaving directory `tmp/libevent-2.1.8-stable'
make: *** [all] Error 2
Exit 2

% echo $CC
gcc

% gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=gcc/4.5.1-rhel6/x86_64/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.5.1/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --prefix=gcc/4.5.1-rhel6/x86_64 --with-gmp=4.5.1-rhel6/x86_64 --with-mpfr=gcc/4.5.1-rhel6/x86_64 --with-mpc=gcc/4.5.1-rhel6/x86_64 --with-ppl=gcc/4.5.1-rhel6/x86_64 --with-libelf=gcc/4.5.1-rhel6/x86_64
Thread model: posix
gcc version 4.5.1 (GCC)
