### ISSUE TITLE
When link with libevent_openssl.a, it reports the following error:

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#974]
```
../work/libs/libevent_openssl.a(libevent_openssl_la-bufferevent_openssl.o): In function `bio_bufferevent_new':
/home/root/libevent-master/bufferevent_openssl.c:112: undefined reference to `BIO_set_init'
/home/root/libevent-master/bufferevent_openssl.c:113: undefined reference to `BIO_set_data'
../work/libs/libevent_openssl.a(libevent_openssl_la-bufferevent_openssl.o): In function `BIO_new_bufferevent':
/home/root/libevent-master/bufferevent_openssl.c:260: undefined reference to `BIO_set_init'
/home/root/libevent-master/bufferevent_openssl.c:261: undefined reference to `BIO_set_data'
/home/root/libevent-master/bufferevent_openssl.c:264: undefined reference to `BIO_set_shutdown'
../work/libs/libevent_openssl.a(libevent_openssl_la-bufferevent_openssl.o): In function `BIO_s_bufferevent':
/home/root/libevent-master/bufferevent_openssl.c:237: undefined reference to `BIO_meth_new'
/home/root/libevent-master/bufferevent_openssl.c:240: undefined reference to `BIO_meth_set_write'
/home/root/libevent-master/bufferevent_openssl.c:241: undefined reference to `BIO_meth_set_read'
/home/root/libevent-master/bufferevent_openssl.c:242: undefined reference to `BIO_meth_set_puts'
/home/root/libevent-master/bufferevent_openssl.c:243: undefined reference to `BIO_meth_set_ctrl'
/home/root/libevent-master/bufferevent_openssl.c:244: undefined reference to `BIO_meth_set_create'
/home/root/libevent-master/bufferevent_openssl.c:245: undefined reference to `BIO_meth_set_destroy'
../work/libs/libevent_openssl.a(libevent_openssl_la-bufferevent_openssl.o): In function `bio_bufferevent_ctrl':
/home/root/libevent-master/bufferevent_openssl.c:193: undefined reference to `BIO_get_data'
/home/root/libevent-master/bufferevent_openssl.c:201: undefined reference to `BIO_set_shutdown'
/home/root/libevent-master/bufferevent_openssl.c:198: undefined reference to `BIO_get_shutdown'
../work/libs/libevent_openssl.a(libevent_openssl_la-bufferevent_openssl.o): In function `bio_bufferevent_read':
```

**Comment by azat** [comment]
And did you link with the `crypto`/`ssl`? Can you provide the linker command?

**Comment by okayabc** [comment]
Yes, makefile like this:

OPENSSL_LIB = -lssl -lcrypto
EVENT_LIB = -levent -levent_extra -levent_core -levent_openssl -levent_pthreads

$(PROJECT) : $(OBJECTS)	
$(LINKER) $(OBJECTS) -o $(WORK)$(PROJECT) -lm -lpthread -ldl $(OPENSSL_LIB) $(EVENT_LIB) -l$(Zlib)

**Comment by azat** [comment]
All the functions from the errors are added in openssl 1.1, and you are trying to build with openssl 1.0

**Comment by okayabc** [comment]
The openssl version of the server is 
OpenSSL 1.1.1d  10 Sep 2019. Maybe the server has openssl1.1 and 1.0, it leads this problem?

**Comment by azat** [comment]
Ok, got it, the problem is that for static libraries order is important, place the openssl libraries after event libraries.

See gcc(1):

```
           It makes a difference where in the command you write this option; the linker searches and processes libraries and object files in the order they are specified.  Thus, foo.o
           -lz bar.o searches library z after file foo.o but before bar.o.  If bar.o refers to functions in z, those functions may not be loaded.
```

**Comment by okayabc** [comment]
A little sad, still report the above error after i adjust the order.

**Comment by azat** [comment]
Are you sure that they are the same (particularly interesting in which functions undefined references are)? Also with which version of openssl your compiled libevent?

**Comment by okayabc** [comment]
Yes, the error is same no matter which order is chosen.
How to see the openssl version used to compile libevent?

**Comment by okayabc** [comment]
If i compile with libevent.a not so on Server A and release it on Server B with different enviroment(such as os version, openssl version etc), can it avoid the issue #971 ?

**Comment by azat** [comment]
No, this still is not enough (since the problem will have abi interface X, while you will provide another and something will be likely broken), but you can use static libssl.a and libcrypto.a this will help (however this will require extra dependencies that are not supplied for .so, so be patient and add them)

**Comment by azat** [comment]
>The openssl version of the server is
OpenSSL 1.1.1d 10 Sep 2019. Maybe the server has openssl1.1 and 1.0, it leads this problem?

So you compiled libevent in the same environment/machine that you are trying to compile the project that uses libevent+openssl? Please give me output of `pkg-config --cflags openssl` and `pkg-config --libs openssl`

**Comment by okayabc** [comment]
Suppose Dir A store libvent.a ...libevent_pthreads.a,,Dir B store libssl.a and libcrypto.a, can you write a link command to compile program no error?

**Comment by azat** [comment]
#### to create static executable you can use:

```
gcc -Ldir_a -Ldir_b -static -levent_core -levent_extra -levent_openssl -lssl -lcrypto /tmp/test.c
```

#### to link only libevent and openssl statically the following should work:

```
gcc -c /tmp/test.c
ld -static -levent_core -levent_extra -levent_openssl -lssl -lcrypto -shared test.o
```

(*I don't remember exact flags to make it in one `gcc` command, but you can google it*)

P.S. But I'm suggesting you to use cmake over writing commands manually or/and makefiles.
P.P.S. It is better to google such questions in future

**Comment by okayabc** [comment]
Ok, i see! I will try to solve it.Thank you!
